# Generated by Django 3.1.13 on 2021-11-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='musique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('link', models.URLField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categorie', verbose_name='Categories')),
            ],
        ),
    ]
