# Generated by Django 3.1.13 on 2021-11-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mycategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='play',
            field=models.BooleanField(default=False, verbose_name='activate'),
        ),
    ]
