# Generated by Django 3.1.13 on 2021-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_categorie_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='play',
            field=models.BooleanField(default=False, verbose_name='play'),
        ),
    ]
